### ISSUE TITLE
Lesson 3.3 Running Your First Flask App " OSError: [Errno 8] Exec format error "

### ISSUE THREAD

**Issue by B-Harden** [udacity/Full-Stack-Foundations#127]
All of the provided code via Udacity has ran smoothly for me until I got to Lesson 3-3 Running Your First Flask Application. I copied and pasted the 'project.py' code directly from Github. Upon running the code via 'python project.py' in the terminal, I get the following error message. I have no clue what it means. Can someone help? Thanks!

vagrant@vagrant:/vagrant/Database_Files$ python project.py
 * Serving Flask app "project" (lazy loading)
 * Environment: production
   WARNING: Do not use the development server in a production environment.
   Use a production WSGI server instead.
 * Debug mode: on
 * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
 * Restarting with stat
Traceback (most recent call last):
  File "project.py", line 12, in <module>
    app.run(host='0.0.0.0', port=5000)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 943, in run
    run_simple(host, port, self, **options)
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/serving.py", line 988, in run_simple
    run_with_reloader(inner, extra_files, reloader_interval, reloader_type)
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/_reloader.py", line 332, in run_with_reloader
    sys.exit(reloader.restart_with_reloader())
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/_reloader.py", line 176, in restart_with_reloader
    exit_code = subprocess.call(args, env=new_environ, close_fds=False)
  File "/usr/lib/python2.7/subprocess.py", line 523, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/usr/lib/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1343, in _execute_child
    raise child_exception
OSError: [Errno 8] Exec format error

**Comment by dii-gineer** [comment]
Hi!  I removed the debug option and it is now working. 
if __name__ == '__main__':
    #app.debug = True
    app.run(host='0.0.0.0', port=5000)

**Comment by baselrabia** [comment]
I have the same issue, did u get any solution?

**Comment by B-Harden** [comment]
@baselrabia 
Yes, comment out the debug mode option and the code should run correctly.

**Comment by B-Harden** [comment]
@dii-gineer 
Sorry for the late reply but that did the trick. Code is running correctly now. Thanks.
